# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"%\n\x04Note\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x18\n\x08Notename\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\rServerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x63tv\x18\x02 \x01(\t\"*\n\x0eServerResponse\x12\x0b\n\x03\x61ns\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x98\x01\n\nChatServer\x12\x39\n\x0cServerStream\x12\x13.grpc.ServerRequest\x1a\x14.grpc.ServerResponse\x12*\n\nChatStream\x12\x0e.grpc.Notename\x1a\n.grpc.Note0\x01\x12#\n\x08SendNote\x12\n.grpc.Note\x1a\x0b.grpc.Emptyb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_NOTE = DESCRIPTOR.message_types_by_name['Note']
_NOTENAME = DESCRIPTOR.message_types_by_name['Notename']
_SERVERREQUEST = DESCRIPTOR.message_types_by_name['ServerRequest']
_SERVERRESPONSE = DESCRIPTOR.message_types_by_name['ServerResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Note)
  })
_sym_db.RegisterMessage(Note)

Notename = _reflection.GeneratedProtocolMessageType('Notename', (_message.Message,), {
  'DESCRIPTOR' : _NOTENAME,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Notename)
  })
_sym_db.RegisterMessage(Notename)

ServerRequest = _reflection.GeneratedProtocolMessageType('ServerRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVERREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ServerRequest)
  })
_sym_db.RegisterMessage(ServerRequest)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ServerResponse)
  })
_sym_db.RegisterMessage(ServerResponse)

_CHATSERVER = DESCRIPTOR.services_by_name['ChatServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _NOTE._serialized_start=29
  _NOTE._serialized_end=66
  _NOTENAME._serialized_start=68
  _NOTENAME._serialized_end=92
  _SERVERREQUEST._serialized_start=94
  _SERVERREQUEST._serialized_end=137
  _SERVERRESPONSE._serialized_start=139
  _SERVERRESPONSE._serialized_end=181
  _CHATSERVER._serialized_start=184
  _CHATSERVER._serialized_end=336
# @@protoc_insertion_point(module_scope)
